apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: mlb-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.20-192.168.1.30
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: mlb-pool
  namespace: metallb-system
spec:
  ipAddressPools:
  - mlb-pool